name: ðŸ§ª Playwright Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:

      #Capturando mais logs
      - name: Run Playwright tests (with debug)
      run: npx playwright test --reporter=html --trace on
      
      # 1ï¸ Checkout do cÃ³digo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2ï¸ Instalar Node.js (mesma versÃ£o usada localmente)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3ï¸ Instalar dependÃªncias
      - name: Install dependencies
        run: npm ci

      # 4ï¸ Instalar browsers do Playwright
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 5ï¸ Rodar os testes (gera relatÃ³rio HTML)
      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      # 6ï¸ Upload do relatÃ³rio como artefato
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 7
      
      # 7 Iniciar aplicaÃ§Ã£o antes dos testes
      - name: Start application
        run: npm run start &
        env:
          NODE_ENV: test

      # 8 Criar storageState.json vazio (caso nÃ£o exista)
      - name: Ensure storageState.json exists
        run: echo '{"cookies":[],"origins":[]}' > storageState.json